image: composer:latest

before_script:
  - composer install

cache:
  paths:
    - vendor/

# jobs
Linting:
  stage: build
  script:
    - vendor/bin/phplint

Unit Testing:
  stage: test
  script:
    - vendor/bin/phpunit
